In [1]:
import numpy as np

In [2]:
import numpy.linalg as npl

In [3]:

a=np.eye(3) #n*n 단위행렬 생성 
print('a\n',a)

b=np.array([[1,3],[2,4]])
print('b\n',b)
print('역행렬\n',npl.inv(b)) #b의 역행렬 B*B^-1=I B행렬 * B역행렬=단위행렬


a
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
b
 [[1 3]
 [2 4]]
역행렬
 [[-2.   1.5]
 [ 1.  -0.5]]


In [5]:
a=np.arange(12).reshape(3,4)
b=np.arange(24).reshape(2,4,3)
print(a)
print(a.T) #A행렬의 전치행렬 구하기 전치행렬->행과열을 바꾼다


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [7]:
a=np.arange(24).reshape(2,4,3)
print(a,'\n')
print(np.transpose(a,(2,0,1))) # (3,2,4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 

[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


In [9]:
a=np.arange(1,10).reshape(3,3)
print(a,'\n') 
b=np.diag(a) #대각원소
print(b,'\n')
c=np.trace(a) #대각원소들의합
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 5 9] 

15


In [22]:
#최대 최소값의 위치구하기 argmax argmin

b=np.random.randint(21,size=20).reshape(4,5)
print(b)
print()
print(f"argmax {np.argmax(b)}")
print(f"argmax axis 0 {np.argmax(b,axis=0)}") #axis=0 =>행방향 밑방향으로검사한다
print(f"armax axis 1 {np.argmax(b,axis=1)}") #axis=1 => 열방향 옆방향으로 검사한다

[[16  6 13  9  1]
 [11 20 20  9  8]
 [18 19 13  4  8]
 [13 10  9  4 10]]

argmax 6
argmax axis 0 [2 1 1 0 3]
armax axis 1 [0 1 1 0]
