In [1]:
import numpy as np
import random

### ndarray 생성방법

In [2]:
array_data=np.arange(30).reshape(2,5,3)
print(array_data)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [21]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
a2=np.array([[1,2],[3,4],[5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [4]:
n2=np.linspace(1,100,10).reshape(2,5)
print(n2)

[[  1.  12.  23.  34.  45.]
 [ 56.  67.  78.  89. 100.]]


In [5]:
n3=np.zeros((2,3,5)) # shape (s) 튜플형태로 인자 전달
print(n3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
n4=np.ones((2,2,2))
print(n4)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
n5=np.empty((2,2,2))
print(n5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [8]:
n6=np.full((3,2),5) #shape (s) 튜플형태로전달 ,채울숫자
print(n6)

[[5 5]
 [5 5]
 [5 5]]


### 난수로 ndarray 생성

In [10]:
c=np.random.randint(1,10,size=10).reshape(2,5) #구간 [1,10) 
print(c)

[[4 3 4 4 6]
 [5 8 6 5 7]]


In [17]:
d=np.random.rand(3,2)  #3행2열의  : 0 ~ 1의 균일분포구간안에서 발생 [0,1) 구간
print(d)
print()
e=np.random.sample((3,2)) # radom.rand()동일결과 shaep는 tuple형태로전달
print(e)

[[0.01138804 0.65757877]
 [0.82375795 0.12636385]
 [0.28251828 0.71080792]]

[[0.88518524 0.37938108]
 [0.74093318 0.96831202]
 [0.70592448 0.64049471]]


In [16]:
f=np.random.randn(3,2) #rand와 다르게 가우시안 정규분포 평균 0 분산1 구간에서 발생
print(f)
#random.rand 는 양수만 발생하지만 random.randn 은 평균이 0 분산 1구간에서 전부발생


[[ 0.53288037 -2.00361003]
 [ 1.01667305 -0.3265618 ]
 [-0.64497963  2.35681877]]


### radom 생성 정리
randint(start,end,size=5) -> [start,end) size 갯수만큼 발생  
rand(2,2) -> 2행2열 (0,1]구간안에서 발생  
randn(2,2) -> 2행 2열 평균이 0이고 분산이1인구간에서 발생 

### 행렬의 곱

In [23]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2],[3,4],[5,6]])
dot_arr=np.dot(a1,a2) #행렬의 곱 a1의 열과 a2의 행이 일치해야한다
print(dot_arr)

[[22 28]
 [49 64]]


### 요소 추가,삽입,삭제

In [40]:
array_data_3D=np.arange(30).reshape(2,5,3)
array_data_2D=np.arange(20).reshape(5,4)
print(array_data_2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [41]:
array_data_2D=np.append(array_data_2D,[[0,0,0,0]],axis=0) #axis=0행방향추가 
print(array_data_2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [ 0  0  0  0]]


In [44]:
array_data_2D=np.append(array_data_2D,[[1],[1],[1],[1],[1],[1]],axis=1) #axis=1 열방향추가
print(array_data_2D)

[[ 0  1  2  3  1]
 [ 4  5  6  7  1]
 [ 8  9 10 11  1]
 [12 13 14 15  1]
 [16 17 18 19  1]
 [ 0  0  0  0  1]]


In [48]:
array_data_2D=np.arange(20).reshape(5,4)

In [49]:
array_data_2D=np.insert(array_data_2D,[1,5],-100,axis=0) # [1,5] 행기준 요소를 전부 -100으로채운다
print(array_data_2D)

[[   0    1    2    3]
 [-100 -100 -100 -100]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]
 [-100 -100 -100 -100]]
