In [1]:
import numpy as np
import random

### ndarray의 속성

In [2]:
data=np.random.randint(21,size=12).reshape(4,3) # 구간 0~20 12개발생 4행 3열
print(data)
print(data.ndim) #axis의수 axis=0 axis=1 존재
print(len(data.shape)) #data.ndim 동일작동
print(data.shape) #data의 모양 tuple형태로 출력
print(data.size) #배열요소의 총갯수
print(data.dtype) #배열요소위 자료형
print(data.itemsize) #각 요소의 크기

[[10 17  7]
 [ 3 14  2]
 [10  3  3]
 [17 17  3]]
2
2
(4, 3)
12
int32
4


### ndarray 생성방법

In [3]:
array_data=np.arange(30).reshape(2,5,3) #arange를 사용하는 방법 arange=range와 동일하지만 실수도가능
print(array_data) #구간 0부터 29까지

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [4]:
a1=np.array([[1,2,3],[4,5,6]]) #array(list) 를 사용하는 방법
print(a1)
a2=np.array([[1,2],[3,4],[5,6]]) #no.array(s) 이때 s=list(s)
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
n2=np.linspace(1,100,10).reshape(2,5) #1,100을포함하는 간격은알아서 10개할당
print(n2)

[[  1.  12.  23.  34.  45.]
 [ 56.  67.  78.  89. 100.]]


### np.zeros np.ones np.full

* np.zeros((3,4))
* np.ones((3,4)
* np.full((3,4),1) 3행4을 전부 1로할당
* np.empty((3,4)) 알수없는값으로 3행4열 할당

In [6]:
n3=np.zeros((2,3,5)) # shape (s) 튜플형태로 인자 전달
print(n3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [7]:
n4=np.ones((2,2,2))
print(n4)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [8]:
n5=np.empty((2,2,2))
print(n5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [9]:
n6=np.full((3,2),5) #shape (s) 튜플형태로전달 ,채울숫자
print(n6)

[[5 5]
 [5 5]
 [5 5]]


### 난수로 ndarray 생성

In [10]:
c=np.random.randint(1,10,size=10).reshape(2,5) #구간 [1,10)  1~9까지 size만큼 원소를 생성한다
print(c)

[[4 5 9 5 7]
 [1 4 5 9 1]]


In [11]:
d=np.random.rand(3,2)  #3행2열의  : 0 ~ 1의 균일분포구간안에서 발생 [0,1) 구간
print(d)
print()
e=np.random.sample((3,2)) # radom.rand()동일결과 shaep는 tuple형태로전달
print(e)

[[0.41618265 0.13813028]
 [0.88681796 0.77099146]
 [0.05328396 0.60196059]]

[[0.83731373 0.19794315]
 [0.23093236 0.40486822]
 [0.77078996 0.86910636]]


In [12]:
f=np.random.randn(3,2) #rand와 다르게 가우시안 정규분포 평균 0 분산1 구간에서 발생
print(f)
print()
g=np.random.standard_normal((3,2)) #np.random.randn 동일작동
print(g)
#random.rand 는 양수만 발생하지만 random.randn 은 평균이 0 분산 1구간에서 전부발생


[[-0.20571782  1.33574817]
 [-0.43862979 -1.09263906]
 [-0.86982955 -0.69118981]]

[[-0.4871453   0.07384127]
 [-1.3244275  -1.49271201]
 [ 0.59400955  0.5299537 ]]


### radom 생성 정리
randint(start,end,size=5) -> [start,end)  size 갯수만큼 발생  
rand(2,2) -> 2행2열 (0,1]구간안에서 발생  
randn(2,2) -> 2행 2열 평균이 0이고 분산이1인구간에서 발생 

### 요소들간의 기본연산

In [38]:
a=np.array([10,20,30,40])
b=np.array([20,30,40,50])

print(a+b)
print(a-b)
print(a*b)

[30 50 70 90]
[-10 -10 -10 -10]
[ 200  600 1200 2000]


### 행렬의 곱 =>np.dot(a,b)

In [13]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2],[3,4],[5,6]])
dot_arr=np.dot(a1,a2) #행렬의 곱 a1의 열과 a2의 행이 일치해야한다
print(dot_arr)

[[22 28]
 [49 64]]


### 요소 추가,삽입,삭제

* np.append(arr,value,axis)
* np.insert(arr,index,value,axis)
* np.delete(arr,index,axis)

In [14]:
array_data_3D=np.arange(30).reshape(2,5,3) #0부터29 까지
array_data_2D=np.arange(20).reshape(5,4) #0부터 19까지
print(array_data_3D)
print()
print(array_data_2D)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [15]:
array_data_2D=np.append(array_data_2D,[[0,0,0,0]],axis=0) #axis=0행방향추가 
print(array_data_2D)
#append는 value를 꼭 차원과 동일하게 맞춰서 주어야한다

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [ 0  0  0  0]]


In [16]:
array_data_2D=np.append(array_data_2D,[[1],[2],[3],[4],[5],[6]],axis=1) #axis=1 열방향추가
print(array_data_2D)
#열방향추가시 2차원이니 괄호주의!!!

[[ 0  1  2  3  1]
 [ 4  5  6  7  2]
 [ 8  9 10 11  3]
 [12 13 14 15  4]
 [16 17 18 19  5]
 [ 0  0  0  0  6]]


In [17]:
array_data_2D=np.arange(20).reshape(5,4)

In [18]:
array_data_2D=np.insert(array_data_2D,[1,5],-100,axis=0) # [1,5] 행기준 요소를 전부 -100으로채운다
print(array_data_2D)
#만약 서로 다른 값으로 채우고 싶다면 values를 삽입하려는 axis의 shape에 맞춰서 삽입할 배열을 넣어주면 됩니다.

[[   0    1    2    3]
 [-100 -100 -100 -100]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]
 [-100 -100 -100 -100]]


In [19]:
array_data_2D=np.insert(array_data_2D,0,[0,0,0,0],axis=0)
print(array_data_2D)
print()
array_data_2D=np.insert(array_data_2D,0,[9,9,9,9,9,9,9,9],axis=1)
print(array_data_2D)
#Insert 차원을 맞추지않아도된다 전부 동일값삽입시 valuse 에 숫자한개 할당
#또는 각 칸마다 다른값을 넣을시 axis=n 의 수의 칸에 맞게 할당한다

[[   0    0    0    0]
 [   0    1    2    3]
 [-100 -100 -100 -100]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]
 [-100 -100 -100 -100]]

[[   9    0    0    0    0]
 [   9    0    1    2    3]
 [   9 -100 -100 -100 -100]
 [   9    4    5    6    7]
 [   9    8    9   10   11]
 [   9   12   13   14   15]
 [   9   16   17   18   19]
 [   9 -100 -100 -100 -100]]


In [20]:
array_data_2D=np.arange(20).reshape(5,4)
print(array_data_2D)

array_data_2D=np.insert(array_data_2D,2,-50,axis=1)
print(array_data_2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[  0   1 -50   2   3]
 [  4   5 -50   6   7]
 [  8   9 -50  10  11]
 [ 12  13 -50  14  15]
 [ 16  17 -50  18  19]]


In [21]:
array_data_2D=np.arange(20).reshape(5,4)
print(array_data_2D)
print()
array_data_2D=np.delete(array_data_2D,1,axis=0)
print(array_data_2D)
array_data_2D=np.delete(array_data_2D,0,axis=1)
print()
print(array_data_2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 1  2  3]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]


In [22]:
array_data_2D=np.delete(array_data_2D,2,axis=1)
print(array_data_2D)
#np.delete target 삭제할 인덱스 axis를 준다

[[ 1  2]
 [ 9 10]
 [13 14]
 [17 18]]


In [23]:
array_data_2D=np.delete(array_data_2D,1,axis=1)
print(array_data_2D)

[[ 1]
 [ 9]
 [13]
 [17]]


In [24]:
array_data_2D=np.append(array_data_2D,[[1],[2],[3],[4]],axis=1)
print(array_data_2D)
#append는 기존대상과 차원을 맞추어 삽입한다 열방향 추가b시 주의

[[ 1  1]
 [ 9  2]
 [13  3]
 [17  4]]


### ndarray의 reshape

In [43]:
a=np.arange(12)
print(a)
a.shape=(3,4)
print(a)
b= a.reshape(2,2,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [25]:
nums = np.array(
    [[0,  1,  2],
     [3,  4,  5],
     [6,  7,  8],
     [9, 10, 11]])
print(nums)
print(nums.shape) #(n.m) n행 m열
nums=np.delete(nums,3,axis=0)
print(nums)
print(nums.shape) #튜플형태 (m행,n열) 전달
print(nums.ndim) #2차원 배열
print(len(nums.shape)) #numse.ndim 차원의 갯수와동일
print(nums.size) #배열요소의 갯수
print(nums.itemsize) #배열요소의 자료형 4
print(nums.dtype) #배열요소의 자료형 int 32


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
2
2
9
4
int32
[0 1 2 3 4 5 6 7 8]


### nd array ravel

In [45]:
print(nums.ravel())

[0 1 2 3 4 5 6 7 8]


In [26]:
print(np.sum(nums,axis=0))# axis=0 [0,1,2]->[3,4,5]->[6,7,8]->[9,10,11]
print(np.sum(nums,axis=1)) # axis=1 

[ 9 12 15]
[ 3 12 21]


### Broadcasting

In [27]:
data=np.arange(3).reshape(3,1)+np.arange(3) #(3,1)+(1,3) =(3,3)
print(data)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [28]:
d1=np.random.randint(20,size=10).reshape(2,5)
d2=np.random.randint(20,size=20).reshape(2,2,5)
print(d1)
print("----------------")
print()
print(d2)
d3=d1+d2
print("-----------------")
print(d3) # (2,2,5) 
print(d3.shape)

[[ 3 17  3 11  1]
 [10  9 18 19  1]]
----------------

[[[11  5  4  5  8]
  [ 6 12 13 11 14]]

 [[10 16 19 19  2]
  [14  4  7  5  5]]]
-----------------
[[[14 22  7 16  9]
  [16 21 31 30 15]]

 [[13 33 22 30  3]
  [24 13 25 24  6]]]
(2, 2, 5)


In [29]:
d1=np.arange(20).reshape(5,4) # (5,4)
d2=d1+3 #(3,)+(5,4)
print(d1)
print()
print(d2)
d2=np.arange(3).reshape(3,1,1)
print("d1출력\n",d1)
print("d2출력\n",d2)
res=d1+d2
print(res)# (3,5,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
d1출력
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
d2출력
 [[[0]]

 [[1]]

 [[2]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]

 [[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]]


In [30]:
d1=np.arange(20).reshape(2,2,5)
print(d1)
print(d1.shape)
d2=np.arange(10).reshape(2,5)
print(d2)
print(d2.shape)
d3=d1+d2
print()
print(d3)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
(2, 2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[10 12 14 16 18]
  [20 22 24 26 28]]]


### Numpy Indexing slicing

In [31]:
d1=np.arange(20).reshape(4,5)
print(d1)
print()

print(d1[1:3,1]) #6 11 1,2인덱스를 1열에서 추출한다
print()
print(d1[:2])  #0 1행 전부 출력
print()
print(d1[1:,4]) #1행부터 끝까지 4열에서 출력
print()
print(d1[:,-1]) #마지막열에서 전부출력
print()
print(d1[-1]) #행의 마지막행을 출력한다 d1[:,-1]과 다르게 출력한다
print()
print(d1[-2]) #행 인덱싱
print()
print(d1[-3,-2]) #-3번쨰원소인데 끝에서 2번째열에서 추출한다 햇갈림...
print(d1[-3:,-2]) #-2번쨰열에사 -3부터끝까지 전부출력 8 13 18

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 6 11]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[ 9 14 19]

[ 4  9 14 19]

[15 16 17 18 19]

[10 11 12 13 14]

8
[ 8 13 18]


### copy  boolean indexing  filtering searching 

In [33]:
d1=np.random.randn(3,3)
print(d1)
d2=d1.copy()
print(id(d1)) 
print(id(d2))
# 주소값이 다르다 깊은복사 Numpy copy()사용

[[ 0.54699363  0.33582597  0.10027799]
 [ 1.19181842 -2.07175905 -0.65820272]
 [-0.24242957 -1.57468406  0.21693703]]
2537717410736
2537717412272


In [34]:
#Numpy filtering
arr=np.random.randint(20,size=15) #0~19까지 숫자를 15개만든다
print(arr)
func=arr%2==0
print(arr[func])

[12 11 18 10 10  5 11 17 19  2  5 10 10  8  7]
[12 18 10 10  2 10 10  8]


In [35]:
d1=np.arange(20).reshape(5,4)
print(d1)
print()
rows=np.array([True,False,True,False,True])
res=d1[rows,:]
print(res)
print()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]



In [47]:
arr=np.array([1,2,3,4,5,6,7]) #filter 사용
filter = arr%2 == 0
newarr=arr[filter]
print(newarr)

[2 4 6]


In [36]:
#np.searching
d1=np.array([[1,2,3],[4,3,6],[7,8,9],[3,2,1]])
print(d1)
print()
x=np.where(d1==3)
print(x)  
print(x[0])
print(x[1])

[[1 2 3]
 [4 3 6]
 [7 8 9]
 [3 2 1]]

(array([0, 1, 3], dtype=int64), array([2, 1, 0], dtype=int64))
[0 1 3]
[2 1 0]


In [37]:
data=np.random.randint(20,size=15).reshape(3,5)
print(data)

find=np.where(data==10)
print(find)
print()
p=np.where(data>15)
print(p)

[[17 14 14  7  6]
 [ 4 11  1 13  4]
 [ 1 12 14  4 10]]
(array([2], dtype=int64), array([4], dtype=int64))

(array([0], dtype=int64), array([0], dtype=int64))
